//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mystat.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Day
    {
        public int Id { get; set; }
        public int DayOfWeeksId { get; set; }
        public int LessonId { get; set; }
        public string TimeInterval { get; set; }
    
        public virtual DayOfWeek DayOfWeek { get; set; }
        public virtual Lesson Lesson { get; set; }
    }
}
