//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mystat.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int Id { get; set; }
        public int MaterialStatusId { get; set; }
        public int SubjectId { get; set; }
        public string File { get; set; }
    
        public  MaterialStatu MaterialStatu { get; set; }
        public  Subject Subject { get; set; }
    }
}
