//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mystat.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int Id { get; set; }
        public int PointStatusId { get; set; }
        public int LessonId { get; set; }
        public int StudentId { get; set; }
        public Nullable<int> Point1 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> StudentHomeworkId { get; set; }

        public virtual Lesson Lesson { get; set; }
        public virtual PointStatu PointStatu { get; set; }
        public virtual Student Student { get; set; }
        public virtual StudentHomework StudentHomework { get; set; }
    }
}
