//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mystat.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentHomework
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int HomeworkId { get; set; }
        public DateTime? SentAt { get; set; }
        public string File { get; set; }
        public byte[] FileBytes { get; set; }
        public bool? Checked { get; set; }

        public  Homework Homework { get; set; }
        public  Student Student { get; set; }
        public  ICollection<Point> Points { get; set; }
    }
}
