//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mystat.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Attendances = new HashSet<Attendance>();
            this.Comments = new HashSet<Comment>();
            this.Exams = new HashSet<Exam>();
            this.Points = new HashSet<Point>();
            this.StudentHomeworks = new HashSet<StudentHomework>();
        }
    
        public int Id { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Fullname { get; set; }
        public Nullable<int> DiamondCount { get; set; }
        public Nullable<int> CoinCount { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Education { get; set; }
        public string Email { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastVisited { get; set; }
        public string Facebook { get; set; }
        public string Linkedin { get; set; }
        public string SocialMedia { get; set; }
        public int GeneralPoint { get; set; }
        public string Photo { get; set; }
        public byte[] ImageBytes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam> Exams { get; set; }
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Point> Points { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentHomework> StudentHomeworks { get; set; }
    }
}
