//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mystat.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Comments = new HashSet<Comment>();
            this.Exams = new HashSet<Exam>();
            this.Groups = new HashSet<Group>();
            this.Lessons = new HashSet<Lesson>();
        }
    
        public int Id { get; set; }
        public int PositionId { get; set; }
        public string Fullname { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string HomePhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string ExternalNumber { get; set; }
        public string Email { get; set; }
        public string CorporativeEmail { get; set; }
        public string Address { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Facebook { get; set; }
        public string Linkedin { get; set; }
        public string Twitter { get; set; }
        public string ImagePath { get; set; }
        public byte[] ImageBytes { get; set; }
    
        public  ICollection<Comment> Comments { get; set; }
        public  ICollection<Exam> Exams { get; set; }
        public  ICollection<Group> Groups { get; set; }
        public  ICollection<Lesson> Lessons { get; set; }
        public  Position Position { get; set; }
    }
}
